### ISSUE TITLE
generate_serpinsky Function

### ISSUE THREAD

**Issue by bangyen** [neelgokhale/NumberphileMath#2]
For the function `generate_serpinsky`, are the `if` statements regarding `rel_loc(new_coords)` all supposed to append the same thing?

**Comment by neelgokhale** [comment]
Basically, that if statement checks where the relative location is of a point to its closest vertex. Now that I think about it, it is inefficient to call it 4 times since it gets the same result. Might want to assign it to a var and call it only once.

**Comment by neelgokhale** [comment]
Added changes to all directories.
